### ISSUE TITLE
in sumsung galaxy S3 ui issue

### ISSUE THREAD

**Issue by darin-lao** [Pombo/material-edit-text#1]
![d](https://cloud.githubusercontent.com/assets/5063371/6455767/ada90644-c193-11e4-936b-44fae1ecdc84.png)

in 720*1280 UI odd

**Comment by justbittin** [comment]
I know this is VERY old, but I am seeing this behavior as well.  The text boxes are not displaying properly.

This library is very small, and what I need...

Did you find a solution?  Did anyone?
